services:
  app:
    build:
      context: .
    volumes:
      - ./data:/data  # Это Bind Mounts
    ports:
      - "8000:8000"

  app_vol:
    build:
      context: .
    volumes:
      - app_data:/data  # Это Volume
    ports:
      - "8001:8000"

volumes:
  app_data:
